# See https://docs.pipewire.org/page_man_pipewire-jack_conf_5.html
# You can also set separate rules for specific jack clients.

jack.properties = {
    rt.prio             = 80
    # 512 samples (quantum) at 48000 Hz (sample rate), their ratio gives latency in seconds.
    # A low latency, however, also increases the chance of xruns.
    node.latency        = 512/48000
    node.lock-quantum   = true
}
