#!/bin/bash --
#
# "XDG_CONFIG_HOME"/bash/bash_functions by milsen
#

# alert after command execution with terminal or error icon and command name
# example usage: sleep 10; alert
alert() {
  notify-send --urgency=low \
    -i "$([ $? = 0 ] && echo terminal || echo error)" \
    "$(history|tail -n1|sed -e 's/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//')"
}


# backup data on external hard drive using rsync
backup_rsync() {
  directories="/media/sdb1-usb-Intenso_External"
  directories="$directories /media/sdb-usb-JMicron_Generic_"
  target=""

  for dir in $directories; do
    if [ ! -d "$dir/" ]; then
      echo "No dir "$dir/" found."
    else
      target="$dir"
      break
    fi
  done

  if [ -z "$target" ]; then
    return
  fi

  sudo rsync -aAX \
    --info=progress2,symsafe,stats3 \
    --delete \
    --exclude={"/swapfile","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/var/lib/dhcpcd/*"} \
    --temp-dir="$HOME"/.cache/rsync/tmp/ \
    / "$target"
}


# fuzzy directory-change
cdf() {
  cd *"$1"*/
}


# most frequently used commands
mfu() {
  history | \
    awk '{CMD[$2]++;count++;}END {for (a in CMD)print CMD[a] " "  CMD[a]/count*100 "% " a;}' | \
    grep -v "./" | column -c3 -s " " -t | sort -nr | nl |  head "-n${1:-10}"
}

# general function for system commands
q() {
  case "$1" in
    k|killx)    killall xmonad ;;
    l|lock)     slock ;;
    p|poweroff) xbacklight -set 100; systemctl poweroff ;;
    r|reboot)   systemctl reboot ;;
    s|suspend)  systemctl suspend ;;
    *)          return ;;
  esac
}

weather() {
  curl -s wttr.in/"$1"?"${2:-0}"
}

webcopy() {
  wget --mirror --convert-links --adjust-extension --page-requisites --no-parent "$1"
}

webcam_photo() {
  ffmpeg -f v4l2 -video_size 1280x720 -i /dev/video0 -vframes 1 "${1:-webcam.png}"
}

webcam_film() {
  ffmpeg -f v4l2 -video_size 1280x720 -i /dev/video0 \
    -f alsa -i default  \
    -c:v libx264 -preset ultrafast -c:a aac "${1:-webcam.mp4}"
}
