; Polybar config by milsen
;
; For info on configuration, see
;   https://github.com/polybar/polybar/wiki
; To look up Material icons, see
;   https://fonts.google.com/icons

[colors]
foreground = #c9ccca
primary = #82b8b1
active = #ebc273
alert = #d25d5d
disabled = #7c838b
background = #14181f
background-active = #373b41

[bar/mybar]
width = 100%
height = 24pt
radius = 0

; gap around bar
border-size = 0pt
border-color = #00000000

; spacing
padding-left = 0
padding-right = 1
module-margin = 1
separator = ""
separator-foreground = ${colors.disabled}

; styling
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = Terminus:style=Bold:size=20;2
font-1 = Material Icons:style=Regular:size=15;3
cursor-click = pointer
cursor-scroll = default
line-size = 3pt

; modules
modules-left = i3 xwindow
; modules-center =
modules-right = polypomo battery pulseaudio memory cpu wlan eth space systray space date
; For additional filesystem and brightness info:
; modules-right = polypomo battery filesystem_root filesystem_home pulseaudio backlight memory cpu wlan eth space systray space date

; i3 handling
override-redirect = false
scroll-up = "#i3.prev"
scroll-down = "#i3.next"
; wm-restack = i3

; let this bar receive polybar-msg commands
enable-ipc = true

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/space]
type = custom/text
format = " "

[module/systray]
type = internal/tray
format-margin = 4pt
tray-spacing = 5pt
tray-size = 75%

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.active}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/i3]
type = internal/i3
; Only show workspaces defined on the same output as the bar
; Useful if you want to show monitor specific workspaces.
pin-workspaces = false
show-urgent = false
strip-wsnumbers = false
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = true
reverse-scroll = false

; fuzzy-match = true
; ws-icon-0 = 1;♚
; ws-icon-1 = 2;♛
; ws-icon-2 = 3;♜
; ws-icon-3 = 4;♝
; ws-icon-4 = 5;♞
; ws-icon-default = ♟

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.background}
; Available tokens: %name% %icon% %index% %output%
label-focused = %index%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background-active}
label-focused-underline = ${colors.active}
label-focused-padding = 1
label-unfocused = %index%
label-unfocused-foreground = ${colors.disabled}
label-unfocused-padding = 1
label-visible = %index%
label-visible-underline = ${colors.disabled}
label-visible-padding = 1
label-urgent = %index%
label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.background-active}
label-urgent-underline = ${colors.alert}
label-urgent-padding = 1
label-separator = ""
label-separator-padding = 0
label-separator-foreground = ${colors.disabled}

[module/xwindow]
type = internal/xwindow
label = %title:0:80:...%

[filesystem-base]
type = internal/fs
interval = 25
format-mounted-prefix-foreground = ${colors.primary}
format-unmounted-prefix-foreground = ${colors.disabled}
label-mounted = %percentage_used%%
label-unmounted = N/A
label-unmounted-foreground = ${colors.disabled}

[module/filesystem_root]
inherit = filesystem-base
mount-0 = /
format-mounted-prefix = "/ "
format-unmounted-prefix = "/ "

[module/filesystem_home]
inherit = filesystem-base
interval = 25
mount-0 = /home
format-mounted-prefix = " "
format-unmounted-prefix = " "

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = " %percentage%%"
label-muted-foreground = ${colors.disabled}

[module/backlight]
; ls -1 /sys/class/backlight/  # to list available cards
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format = <label>
label = %percentage%%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.primary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.background-active}

[module/memory]
type = internal/memory
interval = 2
warn-percentage = 80
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format-warn-prefix = " "
format-warn-prefix-foreground = ${colors.alert}
format-warn-foreground = ${colors.alert}
label = %percentage_used:2%%
label-warn = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
warn-percentage = 80
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format-warn-prefix = " "
format-warn-prefix-foreground = ${colors.alert}
format-warn-foreground = ${colors.alert}
label = %percentage:2%%
label-warn = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
format-connected-foreground = ${colors.primary}
format-disconnected-foreground = ${colors.disabled}
; All labels support the following tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %netspeed%  [wireless+wired] (%upspeed% + %downspeed%) (New in version 3.6.0)
;   %linkspeed% [wired]
;   %mac%       [wireless+wired] (New in version 3.6.0)
; To add a clickable: %{A1:nm-connection-editor:} %{A}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = 
label-disconnected = 

[module/eth]
inherit = network-base
interface-type = wired
label-connected = 
label-disconnected = 

[module/date]
type = internal/date
interval = 1
date = %%{F#82b8b1}%d.%m.%{F-}
time = %H:%M:%S
date-alt =
time-alt = %H:%M
; date = %d.%m.%y
; date-alt =
; time =
; time-alt = %H:%M:%S
label = %date% %time%
label-foreground = ${colors.foreground}

[module/battery]
; ls -1 /sys/class/power_supply/  # to list batteries
type = internal/battery
full-at = 100
low-at = 20
battery = BAT0
adapter = ADP1
format-charging = <ramp-capacity> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <ramp-capacity> <label-low>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
label-low = %percentage%%
label-low-foreground = ${colors.alert}
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-1-foreground = ${colors.alert}
ramp-capacity-2-foreground = ${colors.primary}
ramp-capacity-3-foreground = ${colors.primary}
ramp-capacity-4-foreground = ${colors.primary}

[module/mpd]
type = internal/mpd
host = 127.0.0.1
port = 6600
; format-online = <icon-prev> <icon-stop> <toggle> <icon-next> <bar-progress> <label-time> <label-song>
format-online = <icon-prev> <icon-stop> <toggle> <icon-next>
format-offline = <label-offline>
label-song = %artist% - %title%
label-time = %elapsed% / %total%
label-offline = " "
icon-play = 
icon-pause = 
icon-stop = 
icon-next = 
icon-prev = 
icon-seekf = 
icon-seekb = 
icon-random = 
icon-repeat = 
icon-repeatone = 
icon-single = 
icon-consume = 
toggle-on-foreground = ${colors.primary}
toggle-off-foreground = ${colors.disabled}

[module/polypomo]
type = custom/script
exec = $HOME/bin/polypomo
tail = true
label = %output%
click-left = $HOME/bin/polypomo toggle
click-right = $HOME/bin/polypomo end
click-middle = $HOME/bin/polypomo lock
scroll-up = $HOME/bin/polypomo time +60
scroll-down = $HOME/bin/polypomo time -60
