#!/bin/sh
#
# "$XDG_CONFIG_HOME"/wmrc/config by milsen
#

# files used for storing things like window geometry etc.
WMRC_TEMPDIR="$HOME"/.cache/wmrc

# groups
GRPNUM=9

# borders
BW=${BW:-5}                    # border width
ACTIVE=${ACTIVE:-0xebc273}     # border color of active window
INACTIVE=${INACTIVE:-0x3c3732} # border color of inactive window
PULSECOLS=~/.config/wmrc/colors # colors for pulsew
FREQ=0.08                      # frequency to pulse borders

# snapping
TPANEL=40 # height of the top panel
BPANEL=0  # height of the bottom panel
LPANEL=0  # width of the left panel
RPANEL=0  # width of the right panel
GAP=0     # gaps between windows
